[gcp_service_account]
type = "service_account"
project_id = "logical-acolyte-464803-m5"
private_key_id = "74e7544b8c21e059106ee829f0d8cdb6fc253f7f"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w..."
client_email = "dealer-sheet-writer@logical-acolyte-464803-m5.iam.gserviceaccount.com"
client_id = "103493488859817149378"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/dealer-sheet-writer@logical-acolyte-464803-m5.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[auth]
auth_password = "mysecret"