auth_password = "mysecret"

[gcp_service_account]
type = "service_account"
project_id = "logical-acolyte-464803-m5"
private_key_id = "57c147957c94af185571a29e8ee3a5b81ed15807"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC08gL5Lqyci6JH
EaZNUwkV+AwtNVYWMR89VrnijjF+Yvrpdj9sHXgjdhBPvVJoBX1/cb63CO4Lemuf
CW5AI47rJvGwW92Fo1JeEjaPTmpJm07ZX4xhl2oiuFluMNy6gYwc48tMXFqHL89N
dJVUnx9k6twFP4BpCYMiz52YzOt1vIOsMwhuUEHzX0DEwQ38CDSLXEHq5UBAJneG
4WVVTtSvcrF+eosKSMlQvv0nxZj+MCNwk+nmCkEPa4eESc7xI3JNXchZVeojmrSA
YgGFDr9e0ELk5D7rMdyEX19JslsAF1aV4Ept+MGspm2V/j1VziqkW5+7sjUsOcvF
nerosEWVvAgMBAAECggEABAEbFGf2WpyIdyl/1FQ9w5EIC/QTN03XqCQu3EGop2hf
Wc1LyAO68JCgpHMcdhWGWndU8M4EyUI99s4Jn5Jp4PBYBulxieSRt706xzRwC7hL
0r8CPKKnhE8vbiMsr1VF7tm9BQVCMkhaPmznD8avC4JbDiQCnnsfE3p5aAlDk15o
GNJJSntyAJqoFj31ly2suI6uFNcluoEsGZ5LJHikH9bjskOwD/anQA5JagARmsdc
7G6WEFJdZqcnazmO3VvCp6J6HJlyZ6vU6mBZ2aaO7KGAJ8IQup/Jw0YKTqP/ZvPF
zOon+QaPPCMnHbOAkZ7G2zzrcN3wx2wTrcit+auGuQKBgQDhsW81LerlVMsgn1uK
teMt9foO3oqTTwMrz667Y15eczSfe2f7rFj9fUDcUXuIiKH5nRbdWVPZQCqQGxVE
H4QibraNp3YiVd3RW1jqT0LhjMMQsdrdaXlVA4ZlKj3llJmL6ab+V8APEPdQHy+x
9a/SrrWduJtKgY+QBWYNlepO3QKBgQDNPk0Se8AP1BAXR5KcjLPIO/B46eTmqeda
DMuQkalIFMKnQSL6Co5TBrQs6CY+UfbyJMUnknY0UvNoE2zGUV1pgwVLr2wMF7aM
B3PH9NO1P5cHu3DZHlAGdnfaK/4DG7x/LmEINzGmbG2kwZjlbvF8BimQusUyFvNZ
mvM9B1NSuwKBgCrVV/vJySjZHOwGEoOS3ZjddCXaSoaGml14PvtFcqWOS9BwxV1Y
alNBsEugE0foVoVfMPW1fFpg+TL8UN7q9FLsnCzqOVtu3HhdU9S0UkcoReUnPBiF
ageecaVFjRXDTBjnsU/YK5UwbR+Bq7WkoUfk7IcQgDh1ul9lBudRKnTpAoGAf1nu
Bs8EoI2sIlXF0h+4GkGe99fhsYKxS/3ufdj0GgbPtWpEYrQUFc5uFANEX50KRrus
Hd7SO6tQ3z5WW0P3W1Xx/kFuIJ7CJWcmX2c5yhgYBbM31XDqpOfzfEuZxKH8N0o2
6RseUq6q5fU+gvZxHszQE77gRzFYdDwiO7cE66sCgYBkVrFYJhLQWZtzeQg26Yp2
gH9bgjjYALJA0QA4DZBVMeMLTu7lJPrXHCOid1LVH/u8rcODZZSWwf3MftkSTxES
cHQ2z3ZX6Dwwcga2cBUhav5oww3z7kBAkX8lrWVb82FinnWgZH9aUru6ThnhXp4w
DN8KabgE9VCmCUs+IXeNAA==
-----END PRIVATE KEY-----"""
client_email = "dealer-sheet-writer@logical-acolyte-464803-m5.iam.gserviceaccount.com"
client_id = "103493488859817149378"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/dealer-sheet-writer@logical-acolyte-464803-m5.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
